### ISSUE TITLE
Indentation issue in process.yaml, outputs should be at the same level as inputs

### ISSUE THREAD

**Issue by gardengeek99** [opengeospatial/ogcapi-processes#213] opened 2021-06-09 20:13 UTC
there is an issue in
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/process.yaml
Look at the indentation. Shouldn't "outputs" be at the same level as "inputs"?
That is causing an issue with my model generation (I use codegen directly from the spec to generate all of my model Java classes in my server implementation).

**Comment by gardengeek99** [comment] 2021-06-09 20:17
See https://github.com/opengeospatial/ogcapi-processes/pull/214

**Comment by gfenoy** [comment] 2021-06-09 20:31
Sorry this has been solved in the swagger directory only by mistake.

**Comment by pvretano** [comment] 2021-06-10 01:05
@gfenoy I don't understand your comment.  Are you saying the issue is fixed by @gardengeek99 PR or not?  I looked at the PR and it looks good to me.  Please confirm so I can merge the PR.

**Comment by jerstlouis** [comment] 2021-06-10 03:02
@pvretano I _think_ @gfenoy was saying only the consolidated files intended for Swagger were fixed, but not the YAML files in `core/openapi/responses/`.

The PR is definitely good and needed because it is still badly broken in https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/process.yaml .

**Comment by pvretano** [comment] 2021-06-10 11:16
PR that fixes the issue merged.

**Closed by pvretano** 2021-06-10 11:16 UTC
